"""MASi Confirmation/Veto Gate.

Called ONLY when the ensemble fires 3/4 or better.
MASi can CONFIRM, VETO, or WARN — it cannot create trades.

Design:
  - Deterministic-first: if LLM fails/times out, returns DEGRADED (signal proceeds)
  - Compact context: ~600 tokens max to keep latency low
  - Uses Kimi K2 from project .env (LLM_BASE_URL / LLM_MODEL_NAME / LLM_API_KEY)
  - Timeout: 12 seconds (configurable)

Returns:
  {
    "verdict":  "CONFIRM" | "VETO" | "WARN" | "DEGRADED",
    "reason":   str,
    "risks":    [str, ...],
    "masi_status": "ok" | "timeout" | "error" | "degraded",
    "latency_ms": int,
  }
"""
from __future__ import annotations

import json
import logging
import os
import time
from pathlib import Path
from typing import Any

_log = logging.getLogger(__name__)

try:
    from dotenv import load_dotenv
    load_dotenv(Path(__file__).resolve().parents[2] / ".env")
except ImportError:
    pass

import requests

LLM_BASE_URL = os.environ.get("LLM_BASE_URL", "https://api.moonshot.ai/v1")
LLM_MODEL    = os.environ.get("LLM_MODEL_NAME", "kimi-k2-0711-preview")
LLM_API_KEY  = os.environ.get("LLM_API_KEY", "")
LLM_TIMEOUT  = int(os.environ.get("MASI_TIMEOUT_SECONDS", "12"))


_SYSTEM_PROMPT = """You are MASi, an expert SPX/SPY intraday trader. You are reviewing a signal generated by a quantitative ensemble system.

Your job: CONFIRM, VETO, or WARN about the trade.

Rules:
- CONFIRM if the setup is clean and conditions align
- VETO if there is a clear structural reason the trade should NOT be taken (e.g. entering into resistance, bad R:R, late in session)
- WARN if you have concerns but the trade can proceed with caution
- You cannot create a new trade — only evaluate the one presented

Respond in strict JSON only:
{
  "verdict": "CONFIRM" | "VETO" | "WARN",
  "reason": "one sentence",
  "risks": ["risk 1", "risk 2"]
}"""


def _build_context(signal: dict, regime: dict | None, futures: dict | None) -> str:
    """Build compact signal context (~400 tokens max)."""
    ticker  = signal.get("ticker", "?")
    action  = signal.get("action", "?")
    price   = signal.get("price", 0)
    entry   = signal.get("entry", 0)
    t1      = signal.get("target_1", 0)
    stop    = signal.get("stop_loss", 0)
    rr      = signal.get("risk_reward", "?")
    conf    = signal.get("confidence", "?")
    bull    = signal.get("votes_bull", 0)
    bear    = signal.get("votes_bear", 0)
    uw      = signal.get("uw_bias", "neutral")
    intra   = signal.get("intraday", {})
    rsi     = intra.get("rsi", "?")
    vs_vwap = intra.get("price_vs_vwap", "?")
    trend   = intra.get("intraday_trend", "?")
    time_et = signal.get("time_et", "?")

    agents  = signal.get("agents", {})
    agent_lines = []
    for name, res in agents.items():
        icon = "✅" if res["vote"] == "bull" else ("❌" if res["vote"] == "bear" else "▪")
        agent_lines.append(f"  {icon} {name}: {res['vote']} (score={res['score']:+d})")

    regime_line = ""
    if regime:
        r = regime.get("regime", "?")
        rc = regime.get("confidence", "?")
        regime_line = f"Daily regime: {r} ({rc}% conf)"

    futures_line = ""
    if futures and futures.get("available"):
        es_p = futures.get("es_price", "?")
        es_v = futures.get("es_vwap", "?")
        nq_p = futures.get("nq_price", "?")
        nq_v = futures.get("nq_vwap", "?")
        futures_line = f"/ES {es_p} vs VWAP {es_v:.0f} | /NQ {nq_p} vs VWAP {nq_v:.0f}"

    ctx = f"""Signal review request [{time_et}]:

Ticker: {ticker} | Action: {action} | Price: ${price:.2f}
Entry: ${entry:.2f} | T1: ${t1:.2f} | Stop: ${stop:.2f} | R:R {rr}
Ensemble: {bull}/4 bull, {bear}/4 bear | Confidence: {conf}
RSI: {rsi} | vs VWAP: {vs_vwap} | Trend: {trend}
UW flow: {uw}
{regime_line}
{futures_line}

Agent votes:
{chr(10).join(agent_lines)}

Should this trade be taken?"""
    return ctx.strip()


def confirm(
    signal: dict,
    regime: dict | None = None,
    futures: dict | None = None,
    timeout: int | None = None,
) -> dict[str, Any]:
    """Run MASi confirmation. Always returns a result — never raises."""
    if not LLM_API_KEY:
        return _degraded("LLM_API_KEY not set")

    context = _build_context(signal, regime, futures)
    t_start = time.time()
    timeout  = timeout or LLM_TIMEOUT

    try:
        r = requests.post(
            f"{LLM_BASE_URL}/chat/completions",
            headers={
                "Authorization": f"Bearer {LLM_API_KEY}",
                "Content-Type": "application/json",
            },
            json={
                "model": LLM_MODEL,
                "messages": [
                    {"role": "system",  "content": _SYSTEM_PROMPT},
                    {"role": "user",    "content": context},
                ],
                "max_tokens": 200,
                "temperature": 0.1,
                "response_format": {"type": "json_object"},
            },
            timeout=timeout,
        )
        latency_ms = int((time.time() - t_start) * 1000)

        if r.status_code != 200:
            return _degraded(f"LLM HTTP {r.status_code}", latency_ms=latency_ms)

        raw = r.json()
        content = raw["choices"][0]["message"]["content"]
        parsed  = json.loads(content)

        verdict = parsed.get("verdict", "WARN").upper()
        if verdict not in ("CONFIRM", "VETO", "WARN"):
            verdict = "WARN"

        return {
            "verdict":    verdict,
            "reason":     parsed.get("reason", ""),
            "risks":      parsed.get("risks", []),
            "masi_status": "ok",
            "latency_ms":  latency_ms,
        }

    except requests.Timeout:
        return _degraded("timeout", latency_ms=int((time.time() - t_start) * 1000))
    except json.JSONDecodeError as e:
        return _degraded(f"json_parse_error: {e}", latency_ms=int((time.time() - t_start) * 1000))
    except Exception as e:
        return _degraded(str(e)[:120], latency_ms=int((time.time() - t_start) * 1000))


def _degraded(reason: str, latency_ms: int = 0) -> dict:
    _log.warning("[masi_confirmer] degraded: %s", reason)
    return {
        "verdict":     "DEGRADED",
        "reason":      reason,
        "risks":       [],
        "masi_status": "degraded",
        "latency_ms":  latency_ms,
    }
